import subprocess
import sys
import re

# This tool was generated by AI, it's not optimal and not the best solution,
# don't ask me how it works, I only use it to speed up picking a classification model for myself

files = [
    "Decision_Tree.py",
    "K_Nearest_Neighbor.py",
    "Kernel_SVM.py",
    "Naive_Bayes.py",
    "Logistic_Regression.py",
    "Random_Forest.py",
    "Support_Vector_Machine.py"
]

results = []

# Matches "accuracy = 0.95", "Accuracy: 0.95", or just "0.95"
accuracy_pattern = re.compile(r"(?:accuracy\s*[:=]\s*)?([0-9]*\.?[0-9]+(?:[eE][+-]?[0-9]+)?)", re.IGNORECASE)

def decode_output(raw_bytes: bytes) -> str:
    for enc in ("utf-8", "cp1252", "latin-1"):
        try:
            return raw_bytes.decode(enc)
        except Exception:
            continue
    return raw_bytes.decode("utf-8", errors="ignore")

for file in files:
    print(f"\n--- Running {file} ---")

    proc = subprocess.run([sys.executable, file], capture_output=True)
    output = decode_output(proc.stdout)
    print(output)

    # Default value
    accuracy = None

    # Try to extract accuracy (take the *last* float, usually the printed score)
    matches = accuracy_pattern.findall(output)
    if matches:
        try:
            accuracy = float(matches[-1])
        except ValueError:
            pass

    results.append((file, accuracy))

# Pick the best model by accuracy
best = max(results, key=lambda x: x[1] or 0)

print("\n=== Results Summary ===")
for name, acc in results:
    acc_display = f"{acc:.4f}" if acc is not None else "N/A"
    print(f"{name:35} Accuracy={acc_display:>8}")

print(f"\nBest model: {best[0]}")
print(f"Accuracy={best[1]:.4f}" if best[1] is not None else "Accuracy=N/A")
