import subprocess
import sys
import re

# This tool was generated by AI, it's not optimal and not the best solution,
# don't ask me how it works, I only use it to speed up picking a regression model for myself

# List of model files to run
files = [
    "decision_tree_regression.py",
    "multiple_linear_regression.py",
    "polynomial_regression.py",
    "random_forest_regression.py",
    "support_vector_regression.py",
]

results = []

# Regex patterns to match R², R2, or R^2 (covers all variants)
r2_pattern = re.compile(r"r[\^²2]?\s*score\s*[:=]\s*([0-9.+-eE]+)", re.IGNORECASE)
adj_r2_pattern = re.compile(r"adjusted\s*r[\^²2]?\s*score\s*[:=]\s*([0-9.+-eE]+)", re.IGNORECASE)

def decode_output(raw_bytes: bytes) -> str:
    for enc in ("utf-8", "cp1252", "latin-1"):
        try:
            return raw_bytes.decode(enc)
        except Exception:
            continue
    return raw_bytes.decode("utf-8", errors="ignore")

for file in files:
    print(f"\n--- Running {file} ---")

    # Run file and capture raw bytes
    proc = subprocess.run([sys.executable, file], capture_output=True)
    output = decode_output(proc.stdout)
    print(output)

    # Default values
    r2 = None
    adj_r2 = None

    # Extract numeric values with regex
    r2_match = r2_pattern.search(output)
    adj_match = adj_r2_pattern.search(output)

    if r2_match:
        try:
            r2 = float(r2_match.group(1))
        except ValueError:
            pass

    if adj_match:
        try:
            adj_r2 = float(adj_match.group(1))
        except ValueError:
            pass

    results.append((file, r2, adj_r2))

# Pick the best model (by R² then Adjusted R²)
best = max(results, key=lambda x: (x[1] or 0, x[2] or 0))

print("\n=== Results Summary ===")
for name, r2, adj in results:
    r2_display = f"{r2:.4f}" if r2 is not None else "N/A"
    adj_display = f"{adj:.4f}" if adj is not None else "N/A"
    print(f"{name:35} R2={r2_display:>8}, Adjusted R2={adj_display:>8}")

print(f"\nBest model: {best[0]}")
print(f"R2={best[1]:.4f}" if best[1] is not None else "R2=N/A")
print(f"Adjusted R2={best[2]:.4f}" if best[2] is not None else "Adjusted R2=N/A")
